trigger:
- main

pool:
  vmImage: 'ubuntu-latest'

steps:
- task: UsePythonVersion@0
  inputs:
    versionSpec: '3.x'
    addToPath: true

- checkout: self

- script: |
    echo "Listing IPs from iplist.txt:"
    cat whitelist/iplist.txt
  displayName: 'List IPs from iplist.txt'

